# Generated by Django 5.2.5 on 2025-11-24 15:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='企業/組織名稱')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('tier', models.CharField(choices=[('FREE', '免費會員 (限10筆)'), ('SILVER', '銀級會員 (限100筆)'), ('ENTERPRISE', '企業會員 (無上限/可共享)')], default='FREE', max_length=20, verbose_name='會員等級')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization', verbose_name='所屬組織')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=255, verbose_name='客戶/牧場名稱')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='所在縣市')),
                ('species', models.CharField(blank=True, choices=[('SWINE', '豬'), ('POULTRY', '家禽'), ('RUMINANT', '反芻'), ('AQUA', '水產'), ('OTHER', '其他')], max_length=20, verbose_name='主要物種')),
                ('scale', models.CharField(blank=True, choices=[('SMALL', '小型 (< 500 頭)'), ('MEDIUM', '中型 (500 - 2000 頭)'), ('LARGE', '大型 (> 2000 頭)')], max_length=20, verbose_name='牧場規模')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '客戶',
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
