# Generated by Django 6.0.1 on 2026-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='nutrient_display_mode',
            field=models.CharField(blank=True, default='basic', max_length=10),
        ),
    ]
