# Generated by Django 5.2.5 on 2025-11-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='標準名稱')),
                ('species', models.CharField(choices=[('SWINE', '豬'), ('POULTRY', '家禽'), ('RUMINANT', '反芻'), ('AQUA', '水產')], max_length=20, verbose_name='物種')),
                ('stage', models.CharField(choices=[('NURSERY', '保育期 (Nursery)'), ('GROWER', '生長期 (Grower)'), ('FINISHER', '肥育期 (Finisher)'), ('GESTATION', '懷孕期 (Gestation)'), ('LACTATION', '泌乳期 (Lactation)'), ('BROILER_STARTER', '肉雞-前期 (Starter)'), ('BROILER_GROWER', '肉雞-中期 (Grower)'), ('BROILER_FINISHER', '肉雞-後期 (Finisher)'), ('LAYER_CHICK', '蛋雞-育雛 (Chick)'), ('LAYER_PULLET', '蛋雞-中雞 (Pullet)'), ('LAYER_LAYING', '蛋雞-產蛋 (Laying)'), ('OTHER', '其他階段')], default='OTHER', max_length=30, verbose_name='生長階段')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備註說明')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否為公用')),
                ('min_crude_protein_percent', models.FloatField(blank=True, null=True, verbose_name='CP Min (%)')),
                ('max_crude_protein_percent', models.FloatField(blank=True, null=True, verbose_name='CP Max (%)')),
                ('min_me_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='ME Min (kcal/kg)')),
                ('min_lysine_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Lys Min')),
                ('min_methionine_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Met Min')),
                ('min_met_cys_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Met+Cys Min')),
                ('min_threonine_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Thr Min')),
                ('min_tryptophan_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Try Min')),
                ('min_calcium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Ca Min')),
                ('max_calcium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Ca Max')),
                ('min_phosphorus_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='P Min')),
                ('min_available_phosphorus_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='Avail P Min')),
                ('max_crude_fiber_percent', models.FloatField(blank=True, null=True, verbose_name='Fiber Max (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_standards', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '營養標準',
                'ordering': ['species', 'stage', 'name'],
            },
        ),
    ]
