# Generated by Django 5.2.5 on 2025-11-24 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrientstandard',
            options={'ordering': ['species', 'stage', 'name']},
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_lysine_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_me_kcal_per_kg',
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_met_cys_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_methionine_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_threonine_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='nutrientstandard',
            name='min_tryptophan_g_per_kg',
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='max_crude_fat_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Fat Max (%)'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_de_pig_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='DE Pig Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_dm_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='DM Min (%)'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_lysine_sid_pig_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Lys Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_lysine_total_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Lys Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_me_broiler_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='ME Broiler Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_me_layer_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='ME Layer Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_me_pig_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='ME Pig Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_met_cys_sid_pig_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID M+C Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_met_cys_total_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total M+C Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_methionine_sid_pig_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Met Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_methionine_total_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Met Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_ne_pig_growth_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='NE Growth Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_ne_pig_sow_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='NE Sow Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_sodium_g_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Na Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_threonine_sid_pig_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Thr Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_threonine_total_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Thr Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_tryptophan_sid_pig_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Trp Min'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_tryptophan_total_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Trp Min'),
        ),
        migrations.AlterField(
            model_name='nutrientstandard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nutrientstandard',
            name='min_phosphorus_g_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total P Min'),
        ),
        migrations.AlterField(
            model_name='nutrientstandard',
            name='species',
            field=models.CharField(choices=[('SWINE', '豬'), ('POULTRY', '家禽'), ('RUMINANT', '反芻'), ('AQUA', '水產'), ('OTHER', '其他')], max_length=20, verbose_name='物種'),
        ),
        migrations.AlterField(
            model_name='nutrientstandard',
            name='stage',
            field=models.CharField(choices=[('NURSERY', '保育期'), ('GROWER', '生長期'), ('FINISHER', '肥育期'), ('GESTATION', '懷孕期'), ('LACTATION', '泌乳期'), ('BROILER_STARTER', '肉雞前期'), ('BROILER_GROWER', '肉雞中期'), ('BROILER_FINISHER', '肉雞後期'), ('LAYER_CHICK', '育雛期'), ('LAYER_PULLET', '中雞期'), ('LAYER_LAYING', '產蛋期'), ('OTHER', '其他')], default='OTHER', max_length=30, verbose_name='生長階段'),
        ),
    ]
