# Generated by Django 5.2.5 on 2025-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_alter_nutrientstandard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientstandard',
            name='stage',
            field=models.CharField(choices=[('NURSERY', '保育期 (Nursery)'), ('GROWER', '生長期 (Grower)'), ('FINISHER', '肥育期 (Finisher)'), ('GESTATION', '懷孕期 (Gestation)'), ('LACTATION', '泌乳期 (Lactation)'), ('BROILER_STARTER', '肉雞-前期 (Starter)'), ('BROILER_GROWER', '肉雞-中期 (Grower)'), ('BROILER_FINISHER', '肉雞-後期 (Finisher)'), ('LAYER_CHICK', '蛋雞-育雛 (Chick)'), ('LAYER_PULLET', '蛋雞-中雞 (Pullet)'), ('LAYER_LAYING', '蛋雞-產蛋 (Laying)'), ('OTHER', '其他階段')], default='OTHER', max_length=30, verbose_name='生長階段'),
        ),
    ]
