# Generated by Django 5.2.5 on 2025-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_alter_nutrientstandard_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientstandard',
            name='stage',
            field=models.CharField(choices=[('NURSERY', '保育期 (Nursery)'), ('GROWER', '生長期 (Grower)'), ('FINISHER', '肥育期 (Finisher)'), ('GESTATION', '懷孕期 (Gestation)'), ('LACTATION', '泌乳期 (Lactation)'), ('BROILER_STARTER', '肉雞-前期 (Starter)'), ('BROILER_GROWER', '肉雞-中期 (Grower)'), ('BROILER_FINISHER', '肉雞-後期 (Finisher)'), ('LAYER_CHICK', '蛋雞-育雛 (Chick)'), ('LAYER_PULLET', '蛋雞-中雞 (Pullet)'), ('LAYER_LAYING', '蛋雞-產蛋 (Laying)'), ('LACTATION_COW_HP', '高泌乳牛 (Lactating Ruminants)'), ('LACTATION_COW_LP', '低泌乳牛 (Lactating Ruminants)'), ('DRY_COW', '乾乳牛 (Dry Cow)'), ('BEEF_CATTLE', '肉牛 (Beef Cattle)'), ('HEIFER', '女牛 (Heifer)'), ('CARNIVOROUS_FISH', '肉食性魚類 (Carnivorous)'), ('HERBIVOROUS_FISH', '草食性魚類 (Herbivorous)'), ('SHRIMP', '蝦類 (Shrimp)'), ('OTHER', '其他階段')], default='OTHER', max_length=30, verbose_name='生長階段'),
        ),
    ]
