# Generated by Django 5.2.5 on 2025-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0005_alter_nutrientstandard_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_lysine_sid_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Lys Min_broiler'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_met_cys_sid_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID M+C Min_broiler'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_methionine_sid_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Met Min_broiler'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_threonine_sid_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Thr Min_broiler'),
        ),
        migrations.AddField(
            model_name='nutrientstandard',
            name='min_tryptophan_sid_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='SID Trp Min_broiler'),
        ),
    ]
