# Generated by Django 5.2.5 on 2025-11-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='配方名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('batch_size', models.FloatField(default=0.0, verbose_name='批次重量 (kg)')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='總成本')),
                ('cost_per_kg', models.FloatField(default=0.0, verbose_name='單價 (元/kg)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='歸屬客戶/牧場')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standards.nutrientstandard', verbose_name='採用標準')),
            ],
            options={
                'verbose_name': '配方',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg', models.FloatField(verbose_name='使用量 (kg)')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formulas.formula')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient', verbose_name='原料')),
            ],
            options={
                'verbose_name': '配方明細',
                'unique_together': {('formula', 'ingredient')},
            },
        ),
    ]
