# Generated by Django 5.2.5 on 2025-11-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='原料名稱')),
                ('category', models.CharField(choices=[('CEREAL', '穀物及其副產品 (Cereal grains)'), ('OIL_SEED', '油籽、油果及其副產品 (Oil seeds/fruits)'), ('LEGUME', '豆類種子 (Legume seeds)'), ('TUBER', '塊莖、塊根及其副產品 (Tubers/roots)'), ('OTHER_SEED', '其他種子與果實 (Other seeds/fruits)'), ('FORAGE', '牧草與粗料 (Forages/roughages)'), ('SUGAR_BYPRODUCT', '製糖工業副產品 (Sugar industry)'), ('FERMENT_BYPRODUCT', '發酵工業副產品 (Fermentation)'), ('MINERAL', '礦物質產品 (Mineral products)'), ('OIL_FAT', '油脂 (Oils and fats)'), ('DAIRY', '乳製品 (Dairy products)'), ('ANIMAL_TERRESTRIAL', '陸生動物產品 (Animal products)'), ('FISH_MARINE', '魚類與海產品 (Fish/marine products)'), ('ADDITIVE', '添加劑/合成氨基酸 (Additives)'), ('OTHER', '其他 (Other)')], default='OTHER', max_length=30, verbose_name='分類')),
                ('cost_per_kg_twd', models.FloatField(default=0, verbose_name='成本 (TWD/kg)')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否為公用')),
                ('share_with_org', models.BooleanField(default=False, verbose_name='分享給企業成員')),
                ('dm_percent', models.FloatField(blank=True, null=True, verbose_name='乾物質 (DM%)')),
                ('crude_protein_percent', models.FloatField(blank=True, null=True, verbose_name='粗蛋白 (CP%)')),
                ('crude_fiber_percent', models.FloatField(blank=True, null=True, verbose_name='粗纖維 (CF%)')),
                ('crude_fat_percent', models.FloatField(blank=True, null=True, verbose_name='粗脂肪 (EE%)')),
                ('ash_percent', models.FloatField(blank=True, null=True, verbose_name='粗灰分 (Ash%)')),
                ('starch_percent', models.FloatField(blank=True, null=True, verbose_name='澱粉 (Starch%)')),
                ('sugar_percent', models.FloatField(blank=True, null=True, verbose_name='糖 (Sugar%)')),
                ('ndf_percent', models.FloatField(blank=True, null=True, verbose_name='中洗纖維 (NDF%)')),
                ('adf_percent', models.FloatField(blank=True, null=True, verbose_name='酸洗纖維 (ADF%)')),
                ('de_pig_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='豬消化能 (DE Pig)')),
                ('me_pig_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='豬代謝能 (ME Pig)')),
                ('ne_pig_growth_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='肉豬淨能 (NE Growth)')),
                ('ne_pig_sow_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='母豬淨能 (NE Sow)')),
                ('me_broiler_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='肉雞代謝能')),
                ('me_layer_kcal_per_kg', models.FloatField(blank=True, null=True, verbose_name='蛋雞代謝能')),
                ('calcium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='鈣 (Ca)')),
                ('phosphorus_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='總磷 (P)')),
                ('available_phosphorus_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='有效磷')),
                ('sodium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='鈉 (Na)')),
                ('chloride_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='氯 (Cl)')),
                ('potassium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='鉀 (K)')),
                ('magnesium_g_per_kg', models.FloatField(blank=True, null=True, verbose_name='鎂 (Mg)')),
                ('iron_mg_per_kg', models.FloatField(blank=True, null=True, verbose_name='鐵 (Fe)')),
                ('copper_mg_per_kg', models.FloatField(blank=True, null=True, verbose_name='銅 (Cu)')),
                ('manganese_mg_per_kg', models.FloatField(blank=True, null=True, verbose_name='錳 (Mn)')),
                ('zinc_mg_per_kg', models.FloatField(blank=True, null=True, verbose_name='鋅 (Zn)')),
                ('selenium_mg_per_kg', models.FloatField(blank=True, null=True, verbose_name='硒 (Se)')),
                ('lysine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總離胺酸 (Lys)')),
                ('methionine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總蛋胺酸 (Met)')),
                ('cystine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總胱胺酸 (Cys)')),
                ('met_cys_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總含硫胺基酸 (M+C)')),
                ('threonine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總羥丁胺酸 (Thr)')),
                ('tryptophan_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總色胺酸 (Trp)')),
                ('valine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總纈胺酸 (Val)')),
                ('isoleucine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總異白胺酸 (Ile)')),
                ('leucine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總白胺酸 (Leu)')),
                ('phenylalanine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總苯丙胺酸 (Phe)')),
                ('tyrosine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總酪胺酸 (Tyr)')),
                ('histidine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總組胺酸 (His)')),
                ('arginine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總精胺酸 (Arg)')),
                ('alanine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總丙胺酸 (Ala)')),
                ('aspartic_acid_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總天門冬胺酸 (Asp)')),
                ('glutamic_acid_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總麩胺酸 (Glu)')),
                ('glycine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總甘胺酸 (Gly)')),
                ('serine_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總絲胺酸 (Ser)')),
                ('proline_total_g_kg', models.FloatField(blank=True, null=True, verbose_name='總脯胺酸 (Pro)')),
                ('lysine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 離胺酸 (Lys)')),
                ('methionine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 蛋胺酸 (Met)')),
                ('met_cys_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID M+C')),
                ('threonine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 羥丁胺酸 (Thr)')),
                ('tryptophan_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 色胺酸 (Trp)')),
                ('valine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 纈胺酸 (Val)')),
                ('isoleucine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 異白胺酸 (Ile)')),
                ('leucine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 白胺酸 (Leu)')),
                ('histidine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 組胺酸 (His)')),
                ('arginine_sid_pig_g_kg', models.FloatField(blank=True, null=True, verbose_name='SID 精胺酸 (Arg)')),
                ('linoleic_acid_g_kg', models.FloatField(blank=True, null=True, verbose_name='亞麻油酸 (C18:2)')),
                ('linolenic_acid_g_kg', models.FloatField(blank=True, null=True, verbose_name='次亞麻油酸 (C18:3)')),
                ('vitamin_e_mg_kg', models.FloatField(blank=True, null=True, verbose_name='維生素 E')),
                ('choline_mg_kg', models.FloatField(blank=True, null=True, verbose_name='膽鹼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'name'), name='unique_user_ingredient')],
            },
        ),
    ]
