# Generated by Django 5.2.5 on 2025-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='available_phosphorus_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='me_broiler_kcal_per_kg',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='alanine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 丙胺酸 (Ala)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amen_broiler_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='肉雞代謝能 (AMEn Broiler)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amen_cockerel_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='公雞/蛋雞代謝能 (AMEn Cockerel)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='arginine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 精胺酸 (Arg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='aspartic_acid_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 天門冬胺酸 (Asp)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='available_p_broiler_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='肉雞有效磷 Avail. P Broiler'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='available_p_cockerel_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='公雞有效磷 Avail. P Cockerel'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cystine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 胱胺酸 (Cys)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='digestible_p_pig_no_phytase_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='豬消化磷 (無植酸酶) DP Pig (no phyt.)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='digestible_p_pig_with_phytase_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='豬消化磷 (含植酸酶) DP Pig (w. phyt.)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='folic_acid_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='葉酸 B9 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glutamic_acid_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 麩胺酸 (Glu)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glycine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 甘胺酸 (Gly)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='histidine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 組胺酸 (His)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='insol_nsp_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='不可溶 NSP'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='isoleucine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 異白胺酸 (Ile)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='leucine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 白胺酸 (Leu)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='lysine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 離胺酸 (Lys)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='me_ruminant_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='反芻代謝能 (ME Ruminant)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='met_cys_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID M+C'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='methionine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 蛋胺酸 (Met)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ne_ruminant_kcal_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='反芻淨能 (NE kcal/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='niacin_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='菸鹼酸 B3 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nsp_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='非澱粉多醣 (NSP%)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='pantothenic_acid_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='泛酸 B5 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='phe_tyr_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID Phe+Tyr'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='phenylalanine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 苯丙胺酸 (Phe)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proline_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 脯胺酸 (Pro)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='riboflavin_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='核黃素 B2 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 絲胺酸 (Ser)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sfa_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='總飽和脂肪酸 (SFA)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sol_nsp_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='水溶性 NSP'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tdf_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='總膳食纖維 (TDF%)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tdn_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='總可消化養分 (TDN%)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='threonine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 羥丁胺酸 (Thr)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tryptophan_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 色胺酸 (Trp)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tyrosine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 酪胺酸 (Tyr)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ufa_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='總不飽和脂肪酸 (UFA)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='valine_sid_poultry_g_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='家禽 SID 纈胺酸 (Val)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_a_kiu_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 A (1000 IU/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_b12_ug_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 B12 (ug/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_d_kiu_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 D (1000 IU/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_k_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 K (mg/kg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='choline_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='膽鹼 (mg/kg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_e_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 E (mg/kg)'),
        ),
    ]
