# Generated by Django 5.2.5 on 2025-11-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_available_phosphorus_g_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='me_layer_kcal_per_kg',
        ),
    ]
