# Generated by Django 5.2.5 on 2026-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('COMMON', '常用原料 (Common)'), ('CEREAL', '穀物 (Cereal)'), ('LEGUME', '豆類 (Legume)'), ('FORAGE', '牧草 (Forages/roughages)'), ('MINERAL', '礦物質/維他命 (Mineral/Vitamins)'), ('OIL_FAT', '油脂 (Oils and fats)'), ('DAIRY', '乳製品 (Dairy products)'), ('ANIMAL_TERRESTRIAL', '動物產品 (Animal products)'), ('ADDITIVE', '添加劑 (Additives)'), ('AMINO_ACID', '合成氨基酸 (Amino acids)'), ('OTHER', '其他 (Other)')], default='OTHER', max_length=30, verbose_name='分類'),
        ),
    ]
