# Generated by Django 6.0.1 on 2026-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_is_common_alter_ingredient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_common',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='biotin_mcg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='生物素 (mcg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_b1_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 B1 (mg/kg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_b6_mg_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='維生素 B6 (mg/kg)'),
        ),
    ]
