# Generated by Django 6.0.5 on 2026-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_ingredient_is_common_ingredient_biotin_mcg_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='phytate_P_g_per_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='植酸磷 (P)'),
        ),
    ]
