# Generated by Django 6.0.1 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_phytate_p_g_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('CEREAL', '穀物 (Cereal)'), ('OIL_SEED', '油籽類 (Oil Seed)'), ('LEGUME', '豆類 (Legume)'), ('PROTEIN', '蛋白質飼料 (Protein Feed)'), ('ENERGY', '能量飼料 (Energy Feed)'), ('OIL_FAT', '油脂 (Oil/Fat)'), ('TUBER', '塊根塊莖 (Tuber/Root)'), ('FORAGE', '牧草 (Forages/roughages)'), ('FISH_MARINE', '魚類/海洋 (Fish/Marine)'), ('ANIMAL_TERRESTRIAL', '陸生動物產品 (Animal products)'), ('DAIRY', '乳製品 (Dairy products)'), ('MINERAL', '礦物質/維他命 (Mineral/Vitamins)'), ('ADDITIVE', '添加劑 (Additives)'), ('AMINO_ACID', '合成氨基酸 (Amino acids)'), ('OTHER', '其他 (Other)')], default='OTHER', max_length=30, verbose_name='分類'),
        ),
    ]
